#page title
page_title: AnyNotes+ • Smart AI Note-Taking App # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id: 6745427912 # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).
ios_app_country: us # Required outside USA. Enter 2 letter country code as in https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2

appstore_link: # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link: # Enter Google Play Store URL.
presskit_download_link: # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file).
  # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon: # assets/appicon.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name: # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price: # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description: Your smart, streamlined note-taking app—capture ideas faster with voice, image, and text, powered by AI understanding and search.
app_keywords: smart notes, AI note-taking, voice to text, image recognition, iCloud sync, AnyNotes+, note app
enable_smart_app_banner: true # Set to true to show a smart app banner at top of page on mobile devices.

# Information About Yourself
your_name: Chong Jiang
your_link:
your_city:
email_address: sakeven.jiang@gmail.com
github_username: sakeven


# Feature List                            Edit, add or remove features to be presented.
features:
  - title: Voice-to-Text Capture
    description: Speak your thoughts or to-dos anytime—AnyNotes+ automatically converts your voice into clear, editable text for effortless organization and future search.
    fontawesome_icon_name: microphone

  - title: Photo Recognition & AI Insight
    description: Snap a whiteboard sketch, book page, or handwritten note. Our AI extracts key information from images and turns it into searchable, structured notes.
    fontawesome_icon_name: image

  - title: Pure Text Mode
    description: No distractions, no fuss. Open and start writing in plain text—perfect for daily journaling, brainstorming sessions, and task lists.
    fontawesome_icon_name: font

  - title: Integrated Web Search & AI Answers
    description: Go beyond capturing. Launch web searches or prompt AI-generated content directly from your notes to deepen understanding and enrich your records.
    fontawesome_icon_name: search

  - title: Private iCloud Storage
    description: All notes sync seamlessly to your personal iCloud database—no account registration required. Your data stays yours, across all your Apple devices.
    fontawesome_icon_name: cloud

  - title: Built-In iOS 18 Translation Extension
    description: Translate any voice clip or text on the fly, verify facts with web-based checks, and replace your content in place—all without leaving the app.
    fontawesome_icon_name: globe

# Theme Settings
topbar_color: "#000000"
topbar_transparency: 0.1
topbar_title_color: "#ffffff"

cover_image: assets/headerimage.png # Replace with alternative image path or image URL.
cover_overlay_color: "#363b3d"
cover_overlay_transparency: 0.8

device_color: black # Set to: blue, black, yellow, coral or white.

body_background_color: "#ffffff"

link_color: "#1d63ea"

app_title_color: "#ffffff"
app_price_color: "#ffffff"
app_description_color: "#ffffff"

feature_title_color: "#000000"
feature_text_color: "#666666"

feature_icons_foreground_color: "#1d63ea"
feature_icons_background_color: "#e6e6e6"

social_icons_foreground_color: "#666666"
social_icons_background_color: "#e6e6e6"

footer_text_color: "#666666"

####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
